version: "3.7"
services:
  nginx:
    image: nginx:1.19-alpine
    ports:
      - "80:80"
    volumes:
      - ./configurations/30-sl-nginx.entrypoint.sh:/docker-entrypoint.d/30-sl-nginx.entrypoint.sh:ro
  postfix: # temporary
    image: arugifa/simplelogin-postfix:3.1.0-6
    environment:
      POSTFIX_FQDN: sl.com
      ALIASES_DEFAULT_DOMAIN: sl.com
      DB_NAME: ${POSTGRES_DB}
      DB_HOST: ${POSTGRES_HOST}
      DB_USER: ${POSTGRES_USER}
      DB_PASSWORD: ${POSTGRES_PASSWORD}
      LETSENCRYPT_EMAIL: admin@sl.com
      EMAIL_HANDLER_HOST: email-handler  # Must be identical to the service name
  postgres:  # Must be identical to the .env POSTGRES_HOST variable
    image: postgres:12.1
    environment:
      POSTGRES_USER:
      POSTGRES_PASSWORD: 
      POSTGRES_DB:
    volumes:
      - pgdata:/var/lib/postgresql/data
  webapp:
    build: .
    env_file:
      - .env
    environment:
      DB_URI: postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@${POSTGRES_HOST}:5432/${POSTGRES_DB}
  email-handler:
    build: .
    env_file: 
      - .env
    environment:
      DB_URI: "postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@${POSTGRES_HOST}:5432/${POSTGRES_DB}"
      LOCAL_FILE_UPLOAD: "1"
    command: python email_handler.py
volumes: 
  pgdata:
networks:
  sl-network: